name: CI
on:
  pull_request:

jobs:
  DotNetFramework:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: dotnet test dropbox-sdk-dotnet/Dropbox.Api.Unit.Tests --verbosity normal
